# Generated by Django 3.0.2 on 2020-01-21 10:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='historial',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
