# Generated by Django 3.0.2 on 2020-01-21 19:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20200121_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='historial',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
