# Generated by Django 3.0.2 on 2020-01-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_auto_20200123_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='historial',
        ),
        migrations.AddField(
            model_name='paciente',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
