# Generated by Django 3.0.2 on 2020-01-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0010_auto_20200123_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='enfermedades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
