# Generated by Django 3.0.2 on 2020-01-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_auto_20200123_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='actividad_fisica',
            field=models.TextField(blank=True, null=True),
        ),
    ]
