# Generated by Django 3.0.2 on 2020-01-24 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representaciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_representaciones/'),
        ),
        migrations.AlterField(
            model_name='representaciones',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='DietaDia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('almuerzo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almuerzo_plato', to='dietas.Plato')),
                ('cena', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cena_plato', to='dietas.Plato')),
                ('desayuno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desayuno_plato', to='dietas.Plato')),
                ('media_manana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_manana_plato', to='dietas.Plato')),
                ('merienda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merienda_plato', to='dietas.Plato')),
            ],
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('domingo1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domingo1_dietadia', to='dietas.DietaDia')),
                ('domingo2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domingo2_dietadia', to='dietas.DietaDia')),
                ('jueves1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jueves1_dietadia', to='dietas.DietaDia')),
                ('jueves2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jueves2_dietadia', to='dietas.DietaDia')),
                ('lunes1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunes1_dietadia', to='dietas.DietaDia')),
                ('lunes2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunes2_dietadia', to='dietas.DietaDia')),
                ('martes1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='martes1_dietadia', to='dietas.DietaDia')),
                ('martes2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='martes2_dietadia', to='dietas.DietaDia')),
                ('miercoles1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miercoles1_dietadia', to='dietas.DietaDia')),
                ('miercoles2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miercoles2_dietadia', to='dietas.DietaDia')),
                ('sabado1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sabado1_dietadia', to='dietas.DietaDia')),
                ('sabado2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sabado2_dietadia', to='dietas.DietaDia')),
                ('viernes1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viernes1_dietadia', to='dietas.DietaDia')),
                ('viernes2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viernes2_dietadia', to='dietas.DietaDia')),
            ],
        ),
    ]
