# Generated by Django 3.0.2 on 2020-01-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0002_auto_20200124_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='representaciones',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
