# Generated by Django 3.0.2 on 2020-01-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0012_remove_medicion_dieta'),
        ('dietas', '0003_representaciones_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietadia',
            name='almuerzo',
        ),
        migrations.RemoveField(
            model_name='dietadia',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='dietadia',
            name='desayuno',
        ),
        migrations.RemoveField(
            model_name='dietadia',
            name='media_manana',
        ),
        migrations.RemoveField(
            model_name='dietadia',
            name='merienda',
        ),
        migrations.DeleteModel(
            name='Dieta',
        ),
        migrations.DeleteModel(
            name='DietaDia',
        ),
    ]
