# Generated by Django 3.0.2 on 2020-01-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0005_dieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieta',
            name='dia1b_almuerzo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia1b_almuerzo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia1b_cena1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia1b_cena2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia1b_media_manana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia1b_merienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia1b_postre_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia1b_postre_cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia2b_almuerzo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia2b_almuerzo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia2b_cena1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia2b_cena2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia2b_media_manana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia2b_merienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia2b_postre_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia2b_postre_cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia3b_almuerzo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia3b_almuerzo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia3b_cena1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia3b_cena2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia3b_media_manana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia3b_merienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia3b_postre_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia3b_postre_cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4_almuerzo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4_almuerzo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4_cena1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4_cena2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4_media_manana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4_merienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4_postre_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4_postre_cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4b_almuerzo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4b_almuerzo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4b_cena1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4b_cena2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4b_media_manana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4b_merienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4b_postre_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia4b_postre_cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5_almuerzo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5_almuerzo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5_cena1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5_cena2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5_media_manana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5_merienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5_postre_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5_postre_cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5b_almuerzo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5b_almuerzo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5b_cena1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5b_cena2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5b_media_manana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5b_merienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5b_postre_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia5b_postre_cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6_almuerzo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6_almuerzo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6_cena1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6_cena2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6_media_manana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6_merienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6_postre_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6_postre_cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6b_almuerzo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6b_almuerzo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6b_cena1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6b_cena2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6b_media_manana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6b_merienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6b_postre_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia6b_postre_cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7_almuerzo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7_almuerzo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7_cena1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7_cena2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7_media_manana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7_merienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7_postre_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7_postre_cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7b_almuerzo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7b_almuerzo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7b_cena1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7b_cena2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7b_media_manana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7b_merienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7b_postre_almuerzo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
        migrations.AddField(
            model_name='dieta',
            name='dia7b_postre_cena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dietas.Plato'),
        ),
    ]
