# Generated by Django 3.0.2 on 2020-01-24 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0006_auto_20200124_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dieta',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='plato',
            options={'ordering': ['nombre']},
        ),
    ]
