# Generated by Django 3.0.2 on 2020-01-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0009_auto_20200127_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='merienda',
            field=models.CharField(choices=[('SI', 'sí'), ('NO', 'no')], default='NO', max_length=5),
        ),
    ]
