# Generated by Django 3.0.2 on 2020-01-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0010_plato_merienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_platos/'),
        ),
    ]
