# Generated by Django 3.0.2 on 2020-01-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_auto_20200121_2003'),
        ('mediciones', '0002_auto_20200122_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_mediciones', to='pacientes.Paciente'),
        ),
    ]
