# Generated by Django 3.0.2 on 2020-01-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0003_auto_20200122_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
