# Generated by Django 3.0.2 on 2020-01-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0004_auto_20200122_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicion',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='medicion',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
