# Generated by Django 3.0.2 on 2020-01-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0005_auto_20200123_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='perimetro',
        ),
    ]
