# Generated by Django 3.0.2 on 2020-01-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0008_medicion_grasa_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicion',
            name='grasa_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
