# Generated by Django 3.0.2 on 2020-01-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0002_auto_20200124_0939'),
        ('mediciones', '0010_auto_20200123_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='dieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicion_dieta', to='dietas.Dieta'),
        ),
    ]
