# Generated by Django 3.0.2 on 2020-01-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0011_medicion_dieta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicion',
            name='dieta',
        ),
    ]
