# Generated by Django 3.0.2 on 2020-01-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0006_auto_20200124_1447'),
        ('mediciones', '0012_remove_medicion_dieta'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='dieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicion_dieta', to='dietas.Dieta'),
        ),
    ]
